const projects = [
{
    "projectName":"Dear-Diary Mental Health Supervisor",
    "projectDate":"Dec 2020 - Mar 2021",
    "projectDisplay":"1",
    "projectImage":"",
    "projectDescription":"The App aims at helping people to fight from depression and communicate with them. <br/>It was made using ML, Sentiment Analysis, NLTK, Firebase and Kotlin for development rated 4.8/5 on PlayStore.",
    "breifDescription2":"The App aims at helping people to fight from depression and communicate with them at a 1-1 basis alongside giving them suggestions based on their choices which will be taken from the user in various formats such as MCQ for a one time basis and Diary entries of user on a daily basis.<br/> The app aims to help mainly people who are introvert and don't share their emotions easily with others who are depressed.<br/> We aim to uplift their emotions and make world a better place for them.People who are introverts often find it difficult to sustain with their emotions and feelings not heard by others.",
    "breifDescription3":"We aim to provide everyone their own personal friend who shares their joy as well as pain and is there with them perpetually. ",
    "breifDescription1":"Download the app on Playstore: <a href=\"https://play.google.com/store/apps/details?id=com.priyansh.brainrelief&hl=en_US&gl=US\" target=\"_blank\">Here</a>",
    "githubUrl":"https://github.com/priyansh17/BrainRelief",
},
{
    "projectName":"HealthifyMe Medical Chatbot",
    "projectDate":"Sept 2021 - Oct 2021",
    "projectDisplay":"2",
    "projectImage":"",
    "projectDescription":"The proposed concept is to use Artificial Intelligence to construct a health care chatbot system that can diagnose diseases and deliver basic analgesics.<br/>It was made using ML, Python, Decision Trees and Tkinter",
    "breifDescription1":"Health care has become a critical component of our daily lives. People nowadays are preoccupied with domestic and office tasks, and they are becoming increasingly addicted to the Internet.  They don't pay much attention to their well-being. As a result, people avoid going to the doctor for minor issues. It has the potential to turn into a significant issue.<br/>The goal of artificial intelligence (AI) is to replicate human cognitive functions.  It's causing a paradigm shift in healthcare, thanks to the growing availability of healthcare data and the rapid advancement of analytics tools.",
    "breifDescription2":"To respond to user enquiries, the system application employs a question and response protocol in the form of a chatbot. The answer to the question will depend on the user's request.The important keywords are extracted from the sentence and used to answer those sentences. If a match is found, a substantial response will be provided, or comparable responses will be displayed.<br/>Based on user symptoms, the bot will diagnose the type of sickness you have and provide doctor details, analgesics, and nutritional recommendations.",
    "breifDescription3":"The method was created to help consumers save money and time on healthcare because they are unable to visit doctors or specialists when they are in need.",
    "githubUrl":"https://github.com/priyansh17/HealthifyLife_Medical_Chatbot",
},
{
    "projectName":"AI Enabled FinTech B2B Order Management Application",
    "projectDate":"Jan 2021 - Mar 2021",
    "projectDisplay":"3",
    "projectImage":"",
    "projectDescription":"Associated with HighRadius <br/> Created a Bill Management App dashboard using ML, MySQL, JAVA Servlets, JDBC and ReactJS for companies to manage Account receivables.<br/> Deployed an SVM Regressor Model to predict payment dates which had RMSE 0.4.",
    "breifDescription3":"The B2B world operates else from the B2C or C2C world. Businesses work with other businesses on credit. When a buyer business orders commodity from the dealer business, the dealer business issues an tab for that order. This tab contains colorful information like the details of the goods bought and when they should be paid.",
    "breifDescription2":"Dealer business interacts with colorful businesses and sells goods to all of them at colorful times. Hence, the dealer business needs to keep track of the total quantum it owes from all the buyers. This involves keeping track of all checks from all the buyers. The buyer business needs to clear its quantum due before the due date. still, in real- world scripts, the checks aren't always cleared i.e. paid in full quantum by the due date.",
    "breifDescription1":" We had to make a Machine Learning Model to prognosticate the payment date of an tab when it gets created in the system and classify the tab into different pails grounded on the prognosticated payment date, and this whole process should be managed by a beautiful UI.",
    "githubUrl":"https://drive.google.com/drive/folders/1ltniEiw7xzlLd9_6DoP90fPuUbxGolf3?usp=sharing",
},
{
    "projectName":"Virtual Hand Control",
    "projectDate":"Jan 2022 - Feb 2022",
    "projectDisplay":"4",
    "projectImage":"",
    "projectDescription":"This python program allows you to use your hands as mouse and keyboard and play games or perform any other action by sitting back in a relaxed manner just using your hands from a distance accurately upto 1Meter. <br/> The code is optimized to perform detection at max 60FPS. ",
    "breifDescription1":"This Program uses python openCV and samples of images of hands to recognize 64 different points on both your hands to allow you to customize program as to what it does in different scenarios.",
    "breifDescription2":"Using those points I have used the left hand for keyboard and right for mouse. Can be interchanged in code. This allows user to just view the screen from distant position and have control of it.",
    "breifDescription3":"",
    "githubUrl":"https://github.com/priyansh17/VirtualhandControlForGames",
},
{
    "projectName":"PG Life Website",
    "projectDate":"Dec 2021 - Jan 2022",
    "projectDisplay":"5",
    "projectImage":"",
    "projectDescription":"This website allows students to select PG Hostels by searching for them through the city name and applying other filters.<br/> This is made Using HTML, CSS, Bootstrap, MySQL, React JS, PHP and hosted using XAMPP.",
    "breifDescription1":"This Website was built using ReactJS mainly and uses local database. The App was hosted on local environment using XAMPP.",
    "breifDescription2":"I had built this to perfectice ReactJS, NodeJS and get hands on experience.",
    "breifDescription3":"",
    "githubUrl":"https://github.com/priyansh17/PGLife-Webdev-Project",
},
{
    "projectName":"Online Delivery- Restaurant App",
    "projectDate":"Oct 2019 - Nov 2019",
    "projectDisplay":"6",
    "projectImage":"",
    "projectDescription":"This App built on Android studio using Kotlin was my first Android full stack App.<br/>This App is similar to Swiggy/Zomato or other delivery apps and uses firebase to store and fetch Information.",
    "breifDescription1":"The Idea to build this app was to practice and perfectice my Android development skills.",
    "breifDescription2":"The App uses online database as Google firebase and Kotlin for frontend backend. It contains all the features as adding to card, viewing all hotels, selecting from a range of them and modifying your favourite wishlist.",
    "breifDescription3":"",
    "githubUrl":"https://github.com/priyansh17/Restaurant-App-FoodApp",
},
];

export default projects;